server:
  port: 8081

logging:
  level:
    root: DEBUG




spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fileoperation?useSSL=false
    username: root
    password: root



  jpa:
    hibernate:
      ddl-auto: update

